### ISSUE TITLE
How to use exporter

### ISSUE THREAD

**Issue by Kwamena-S** [UgnisSoftware/ugnis#16]
This is probably a noob question and I know Ugnis is still in alpha but, after creating a new component, how does one pass it's definition to the exporters so it returns React/React Native Components?

**Comment by masiulis** [comment]
https://medium.com/@karolismasiulis/hey-thanks-for-trying-out-ugnis-d255c3d85e4d explains the theory. I would create a script and run it with node:

```javascript 
const fs = require('fs')	
const reactExporter = require('./src/exporters/react')
const reactNativeExporter = require('./src/exporters/react-native')

fs.readdirSync('./ugnis_components/').forEach(file => {
    const definition = JSON.parse(fs.readFileSync('./ugnis_components/'+file, 'utf8'))
    
    // export all components to React
    fs.writeFile(definition.reactPath+ file.slice(0, -4) + "js", reactExporter(definition), function(err) {
         if(err) {
             return console.log(err);
         }
    });
    //  export all components to React Native
    fs.writeFile(definition.reactNativePath + file.slice(0, -4) + "js", reactNativeExporter(definition), 
      function(err) {
         if(err) {
             return console.log(err);
         }
     });
})
```

Should export all files from ugnis_components to react/ and react-native/ directories. Haven't tried this, so it might contain bugs, as I don't really have time to get back into Ugnis this week.

**Comment by masiulis** [comment]
Input bug was fixed with https://github.com/UgnisSoftware/ugnis/commit/13d12294fdd24c84940d97f53c025f91b991b1e7
