### ISSUE TITLE
How to Export ?

### ISSUE THREAD

**Issue by michaeldong** [UgnisSoftware/ugnis#17]
Hi Thank for your project!
The document say:
------
Ugnis consists of three parts:

Declarative definition of your Component.
Visual editor that changes the definition.
Exporters for each supported framework that take the definition and generate code.
------

wonder the third step.  How to export for React Native or React？

I can't find in your document.

**Comment by michaeldong** [comment]
Server.dev.js  don't not use below ?

const reactExporter = require('./src/exporters/react')
const reactNativeExporter = require('./src/exporters/react-native')

reactExporter , reactNativeExporter?

**Comment by masiulis** [comment]
Hi, thanks for trying it out! 

I have update readme with instructions.

There is a general explanation of how it's done in this chain of links https://github.com/UgnisSoftware/ugnis/issues/16

**Comment by michaeldong** [comment]
Thanks for your quick reply. @masiulis .
Your latest readme solve my question. Thanks again. 
Hope for ugins become greater. 👍
