### ISSUE TITLE
how to remove events

### ISSUE THREAD

**Issue by ghost** [UgnisSoftware/ugnis#2]
see in the following screenshot. I added an event which sets `foo = true` and now I want to remove it. How would I do that?

![remove](https://user-images.githubusercontent.com/5035719/29433955-0b792732-8356-11e7-8e22-5960e9949386.PNG)

**Comment by masiulis** [comment]
Working on this, should land sometime next week with branching (if/else) inside components update. For now, you can drag foo onto true, so the event would be foo=foo and do nothing.

**Comment by masiulis** [comment]
Fixed, there is now a button to remove mutations from events. Design is still terrible, but we will get around to that in a month.
